
proxy_cache_path /var/cache/nginx/user_data
    levels=1:2
    keys_zone=user_data_cache:8m
    inactive=5m
    max_size=256m
    use_temp_path=off;

proxy_cache_path /var/cache/nginx/wallet
    levels=1:2
    keys_zone=wallet_cache:4m
    inactive=2m
    max_size=128m
    use_temp_path=off;

map $request_method $skip_cache_by_method {
    default 1;  
    GET     0; 
}


map "$skip_cache_by_method:$http_cache_control" $no_cache {
    default          0;
    "0:no-cache"     1;
    "0:no-store"     1;
    ~^1              1;   # any non-GET
}
